Disable tests, don't install jdk/ndk/gradle by ourselves in manual build action

diff --git a/.github/workflows/manual-build.yml b/.github/workflows/manual-build.yml
--- a/.github/workflows/manual-build.yml
+++ b/.github/workflows/manual-build.yml
@@ -10,35 +10,38 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'temurin'
-
-    - name : install ndk
-      run: | 
-        sudo curl --silent --show-error --location --fail --retry 3 \
-          --output /tmp/$NDK_VERSION.zip \
-          https://dl.google.com/android/repository/$NDK_VERSION-linux-x86_64.zip
-
-        sudo rm -rf $ANDROID_SDK_ROOT/ndk-bundle
-        sudo unzip -q /tmp/$NDK_VERSION.zip -d $ANDROID_SDK_ROOT
-        sudo mv $ANDROID_SDK_ROOT/$NDK_VERSION $ANDROID_SDK_ROOT/ndk-bundle
-        sudo chown -R root:root $ANDROID_SDK_ROOT/ndk-bundle
-        sudo rm -f /tmp/$NDK_VERSION*
-
-        if [[ -d $ANDROID_SDK_ROOT/ndk-bundle && \
-          -n "$(ls -A $ANDROID_SDK_ROOT/ndk-bundle)" ]]; then
-          echo "Android NDK installed"
-        else
-          echo "Android NDK did not install successfully"
-          exit 1
-        fi
-      env:
-        NDK_VERSION: android-ndk-r18b
-
-    - name: Build with Gradle
-      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
-      with:
-        arguments: build
+#    - name: Set up JDK 11
+#      uses: actions/setup-java@v3
+#      with:
+#        java-version: '11'
+#        distribution: 'temurin'
+#
+#    - name : install ndk
+#      run: | 
+#        sudo curl --silent --show-error --location --fail --retry 3 \
+#          --output /tmp/$NDK_VERSION.zip \
+#          https://dl.google.com/android/repository/$NDK_VERSION-linux-x86_64.zip
+#
+#        sudo rm -rf $ANDROID_SDK_ROOT/ndk-bundle
+#        sudo unzip -q /tmp/$NDK_VERSION.zip -d $ANDROID_SDK_ROOT
+#        sudo mv $ANDROID_SDK_ROOT/$NDK_VERSION $ANDROID_SDK_ROOT/ndk-bundle
+#        sudo chown -R root:root $ANDROID_SDK_ROOT/ndk-bundle
+#        sudo rm -f /tmp/$NDK_VERSION*
+#
+#        if [[ -d $ANDROID_SDK_ROOT/ndk-bundle && \
+#          -n "$(ls -A $ANDROID_SDK_ROOT/ndk-bundle)" ]]; then
+#          echo "Android NDK installed"
+#        else
+#          echo "Android NDK did not install successfully"
+#          exit 1
+#        fi
+#      env:
+#        NDK_VERSION: android-ndk-r18b
+#
+#    - name: Setup Gradle
+#      uses: gradle/gradle-build-action@v2
+#      with:
+#        gradle-version: 6.5
+    
+    - name: Execute Gradle build
+      run: ./gradlew --no-daemon assembleDebug
